name: release-please

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
 release-please:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
